name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - run: npm run lint --if-present
      - run: npm run build --if-present
      - run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v6
        with:
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: NODE_TEST_MINIFIED=1 npm test
