name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
